version: "3.9"

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=moysklad
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moysklad
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: