server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moysklad
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    path match:
      matching-strategy: ant_path_matcher